sudo: required
dist: trusty
language: generic

env:
  global:
    - PLAYBOOK="provisioning/provision.yml"
    - INVENTORY="provisioning/inventory"
    - LIMIT="local"
    - SKIP_TAGS=""
    - VERBOSE="vvv"
    - PROVIDER="travis"

# script:
#   - sudo ln -s $TRAVIS_BUILD_DIR /vagrant
#   - cd /vagrant && sudo bash ./deployment/ansible.sh
#   - sudo ./script/run-tests.sh

deploy:
  provider: script
  script: script/deploy-prod.sh
  on:
    branch: feature/master-deploy

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/37692dce0ad99c8a2c7d
    on_success: change
    on_failure: always
    on_start: never
