sudo: required
dist: trusty
language: generic

env:
  global:
    - PLAYBOOK="provisioning/provision.yml"
    - INVENTORY="provisioning/inventory"
    - LIMIT="local"
    - SKIP_TAGS=""
    - VERBOSE="vvv"
    - PROVIDER="travis"

script:
  - sudo ln -s $TRAVIS_BUILD_DIR /vagrant
  - cd /vagrant && sudo bash ./deployment/ansible.sh
  # - sudo ./script/run-tests.sh
  - cat /var/log/upstart/cocorico-*
  - cat /opt/cocorico/log/*.log
  - forever list
  - curl -X GET https://local.cocorico.cc/api/user/me --insecure -v
  - curl -X GET https://127.0.0.1/api/user/me --insecure -v
  - curl -X GET https://0.0.0.0/api/user/me --insecure -v
  - curl -X GET https://localhost/api/user/me --insecure -v

deploy:
  provider: script
  script: script/deploy-prod.sh
  on:
    branch: master

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/37692dce0ad99c8a2c7d
    on_success: change
    on_failure: always
    on_start: never
