environment_name: local
front_hostname: local.cocorico.cc
front_web_public_host: "{{ front_hostname }}"
hostname: "{{ front_hostname }}-{{ environment_name }}"
is_development_environment: yes
http_protocol_prefix: https

capabilities:
  user:
    sign_in: no
  step:
    draft: yes
    review: yes
    debate: yes
    vote: yes
    published: yes
  proposal:
    create: no
    read: no
    vote: no
  article:
    vote: no
  source:
    create: yes
    read: yes
    vote: yes
    community: yes
    bill: no
    num_items_per_page: 5
  argument:
    create: no
    read: no
    vote: no
  vote_card:
    print: no
    scan: no
    download: yes
  vote:
    create: yes
    read: yes
    update: yes
    delete: no
    enabled: yes
    cancel: no
    check_referer: no

mongodb_database_name: "{{ project_name }}"

franceconnect_client_id: 10e0a74c752107f712b890e6183b03b179146eb682189c3158370cb8f3fe7068
franceconnect_client_secret: 9ecc4856675778548fae7c3042b07df78a5134f3ab9ae09b91543965b24f04a3
franceconnect_url: https://fcp.integ01.dev-franceconnect.fr

facebook_client_id: #142422522809982
facebook_client_secret: #8f0812597bdc510a32f27e79b77f4b21

google_client_id: #1048827102701-6gbl2i586oqoj9a9p1u620u0pom399gu.apps.googleusercontent.com
google_client_secret: #U5YibRB5qJn1tvJ-C_3M_I8b

api_web_admin_email: "admin@{{ front_hostname }}"
api_web_admin_password: admin
api_web_admin_name: Admin
api_web_upload_dir: upload

ethereum_etherbase_password: "test"
ethereum_etherbase_balance: "10015200000000000000000"
ethereum_genesis_difficulty: "0x40000"
ethereum_genesis_gas_limit: "0x8FCF88"
ethereum_target_gas_limit: "0x8FCF88"
ethereum_network_id: 424242
ethereum_miner_threads: 1
ethereum_rpc_private_host: 127.0.0.1
ethereum_rpc_private_port: 8545
ethereum_rpc_public_url: "{{ http_protocol_prefix }}://{{ front_web_public_host }}/blockchain/"
ethereum_datadir: "{{ project_dir }}/blockchain/data"
ethereum_mine_on_boot: yes
ethereum_max_peers: 0

certbot_enabled: no

test_app:
  title: Test
  url: https://localhost
  secret: r6rxtuuwhdnb3qixltd7hbiu5wxtdfda

ballot_consumer_count: 1
vote_consumer_count: 1

whitelisted_ips:
  - 192.168.50.1
  - 127.0.0.1
