- set_fact: role_name=app-web

- name: install nodejs
  include: ../../../tasks/install_node.yml

- name: create www root folder
  file: path={{ www_dir }} state=directory

- name: link www project root folder
  file: src={{ cocorico_app_dir }}/public dest={{ www_dir }}/{{ role_name }} state=link

# Windows hosts won't handle creating an actual dir, but it's ok to create a symlink
- file: path={{ project_dir }}/{{ role_name }}/node_modules state=directory recurse=yes
- file: src={{ project_dir }}/{{ role_name }}/node_modules dest={{ cocorico_app_dir }}/node_modules state=link

- name: install npm modules
  npm: path={{ cocorico_app_dir }}

- name: generate app configuration
  template: src=config.json.j2 dest={{ project_dir }}/{{ role_name }}/config.json

- name: build debug app
  shell: npm run build
  args:
    chdir: "{{ cocorico_app_dir }}/"
    creates: "{{ cocorico_app_dir }}/public/app.js"
  register: result
  failed_when: result.stderr
  when: is_development_environment

- name: build release app
  shell: npm run build-release
  args:
    chdir: "{{ cocorico_app_dir }}/"
    creates: "{{ cocorico_app_dir }}/public/app.js"
  register: result
  failed_when: result.stderr
  when: not is_development_environment

- name: install site configuration
  template: src={{ role_name }}.apache.conf.j2 dest=/etc/apache2/sites-available/cocorico-front-web-include/{{ project_name }}-{{ role_name }}.conf
  notify:
    - restart apache2 service
